export const sx = {
  hero: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 6,
    mb: 4,
    minHeight: 320,
    display: "flex",
    alignItems: "flex-end",
    color: "common.white",
    background:
      "linear-gradient(135deg, rgba(15, 23, 42, 0.86) 0%, rgba(30, 41, 59, 0.64) 46%, rgba(180, 83, 9, 0.22) 100%)",
  },
  heroImage: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  heroOverlay: {
    position: "absolute",
    inset: 0,
    background:
      "linear-gradient(180deg, rgba(15, 23, 42, 0.08) 0%, rgba(15, 23, 42, 0.8) 70%, rgba(15, 23, 42, 0.94) 100%)",
  },
  heroContent: {
    position: "relative",
    zIndex: 1,
    p: { xs: 3, md: 5 },
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 1.5,
  },
  heroMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: 1,
    mt: 2,
  },
  header: {
    mb: 4,
  },
  subtitle: {
    color: "text.secondary",
    maxWidth: 760,
    mt: 1,
  },
  categories: {
    display: "flex",
    flexWrap: "wrap",
    gap: 1,
    mt: 3,
  },
  categoriesGrid: {
    display: "grid",
    gridTemplateColumns: {
      xs: "1fr",
      md: "repeat(2, minmax(0, 1fr))",
    },
    gap: 2,
    mb: 4,
  },
  categoryCard: {
    display: "grid",
    gridTemplateColumns: "108px minmax(0, 1fr)",
    gap: 2,
    alignItems: "stretch",
    p: 1,
    borderRadius: 4,
    cursor: "pointer",
  },
  categoryImage: {
    width: "100%",
    height: 96,
    objectFit: "cover",
    borderRadius: 12,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: {
      xs: "1fr",
      md: "repeat(2, minmax(0, 1fr))",
      xl: "repeat(3, minmax(0, 1fr))",
    },
    gap: 3,
  },
  card: {
    display: "flex",
    flexDirection: "column",
    borderRadius: 4,
    overflow: "hidden",
    height: "100%",
  },
  media: {
    width: "100%",
    height: 220,
    objectFit: "cover",
  },
  cardContent: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    flexGrow: 1,
  },
  badgeRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 1,
    mb: 1,
  },
  cardFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 2,
    mt: "auto",
  },
} as const;
